import type { Metadata } from "next";
import {Manrope, Nunito } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
  variable: "--font-nuito",
  subsets: ["latin"],
})

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${nunito.variable}antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
